server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8


spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bicycstore?characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:


mybatis-plus:

  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false


